# Generated by Django 4.2.6 on 2023-10-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
        ('my_cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parks.parkmodel'),
            preserve_default=False,
        ),
    ]
