# Generated by Django 4.2.6 on 2023-10-16 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
        ('my_cars', '0002_carmodel_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='parks.parkmodel'),
        ),
    ]
