# Generated by Django 4.2.6 on 2023-10-16 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cars', '0003_alter_carmodel_park'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A_Z][a-zA-Z]\\d{1,20}$', 'First letter must be uppercase, 1-20 symbols overall length')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine_volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.8), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
