# Generated by Django 4.2.6 on 2023-11-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('id',)},
        ),
    ]
