# Generated by Django 4.2.6 on 2023-10-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Park',
            new_name='ParkModel',
        ),
    ]
