# Generated by Django 4.2.6 on 2023-10-16 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_parkmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmodel',
            name='park_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A_Z][a-zA-Z]\\d{1,20}$', 'First letter must be uppercase, 1-20 symbols overall length')]),
        ),
    ]
